<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

		<AssemblyVersion>0.0.0.0000</AssemblyVersion>
		<FileVersion>0.0.0.0000</FileVersion>
		<VersionPrefix>0.0.0.00000000</VersionPrefix>
		<VersionSuffix>debug</VersionSuffix>

		<Authors>Hgnim, Evian</Authors>
		<Company>$(Authors)</Company>
		<Owners>$(Authors)</Owners>
		<Copyright>Copyright (C) 2025 $(Authors), All rights reserved.</Copyright>
		<PackageLicenseExpression>GPL-3.0</PackageLicenseExpression>
		<Product>LuckyGame</Product>
		<Title>"幸运游戏"桌宠插件</Title>
		<AssemblyTitle>$(Title)</AssemblyTitle>
		<Description>LuckyGame</Description>
		<AssemblyName>VPet.Plugin.LuckyGame</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
		<PackageReference Include="VPet-Simulator.Core" Version="1.1.0.52">
			<ExcludeAssets>runtime;native</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="VPet-Simulator.Windows.Interface" Version="1.1.0.52">
			<ExcludeAssets>runtime;native</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="LinePutScript" Version="1.11.9">
			<ExcludeAssets>runtime;native</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="LinePutScript.Localization.WPF" Version="1.0.7">
			<ExcludeAssets>runtime;native</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<!--在输出后只保留win-x64和win-x86的依赖-->
	<Target Name="RuntimeClear" AfterTargets="AfterBuild">	
		<Message Text="开始清理不需要的runtime..." Importance="high" />

		<RemoveDir Directories="$(OutputPath)/runtimes/linux-x64" />
		<RemoveDir Directories="$(OutputPath)/runtimes/osx-x64" />

		<Message Text="runtime清理完成" Importance="high" />
	</Target>
	<!--在Release编译时清理无用的输出文件-->
	<!--<Target Name="RemoveOtherFile" AfterTargets="AfterBuild" Condition="'$(Configuration)'=='Release'">
		<Message Text="当前为Release模式，开始清理无用的输出文件..." Importance="high" />

		<Delete Files="$(OutputPath)$(TargetName).pdb"/>
		<Delete Files="$(OutputPath)$(TargetName).deps.json"/>

		<Message Text="无用文件清理完成" Importance="high" />
	</Target>-->
</Project>